### ISSUE TITLE
Change to static methods like Loop::?

### ISSUE THREAD

**Issue by kelunik** [amphp/file#15]

**Comment by bwoebi** [comment]
Is there any concrete advantage?

**Comment by kelunik** [comment]
Having encapsulation and different getters and setters.

**Comment by bwoebi** [comment]
It's not more or less encapsulated with the function than with a static one.

Also, I see no benefit in having different getters and setters. The current solution works pretty nicely and has no drawbacks to me.

Changing it just for the sake of using a static accessor doesn't make much sense to me.
