### ISSUE TITLE
Add optional time parameters to touch function

### ISSUE THREAD

**Issue by krlv** [amphp/file#21]
PHP's built-in [touch function](http://php.net/manual/en/function.touch.php#refsect1-function.touch-parameters) has 2 optional parameter:
* `time`
The touch time. If time is not supplied, the current system time is used.
* `atime`
If present, the access time of the given filename is set to the value of `atime`. Otherwise, it is set to the value passed to the `time` parameter. If neither are present, the current system time is used.

These parameters are useful for some common use cases and worth to be added to the lib

**Comment by trowski** [comment]
Merged in b67c83752cf986ddee338d1caebfaf993040442c. Thanks!
