### ISSUE TITLE
Non-blocking driver using OS programs and child processes

### ISSUE THREAD

**Issue by joshdifabio** [amphp/file#3]
Is there any reason we couldn't create a new driver which uses amphp/process to invoke OS programs (such as `cat`) in order to provide a non-blocking driver with no dependency on any PHP extensions? This probably wouldn't work as well as libuv but it could act as a nice polyfill.

**Comment by kelunik** [comment]
It's a good idea, but there are a few issues:
* OS programs depend heavily on the platform, a general solution wouldn't be that easy.
* Starting another process for each and every filesystem access will probably be a lot worse than using blocking operations when no extension is available.

I think the usage of blocking operations is a good enough polyfill for development purposes, production systems should anyway have one of the extensions.

**Comment by joshdifabio** [comment]
Thanks for sharing your thoughts. I'll close the issue.
