### ISSUE TITLE
EioDriver is blocking

### ISSUE THREAD

**Issue by andrewmackrodt** [amphp/file#31]
I'm developing a [file system watcher](https://github.com/andrewmackrodt/fsnotify) using Amp and am in the process of replacing blocking file system operations with `amphp/file`. `UvDriver` works ok but has a couple of (c[++]?) extension issues:

1. readlink causes a crash when a path does not exist
1. scandir on an empty directory causes an error
1. stat returns an invalid definition (link instead of nlink)

So I'd like to use EioDriver. However, it appears to be blocking. I have a repository [andrewmackrodt/filesystem](https://github.com/andrewmackrodt/filesystem) which demonstrates the issue.

**Reproduction steps:**

**uv and eio extensions must be installed before proceeding**

```sh
# checkout and initialize the project
git clone https://github.com/andrewmackrodt/filesystem.git
cd filesystem
composer install

# run the scandir test using the default driver (uv)
php test.php

# run the scandir test using eio (eio)
EIO_ENABLED=1 php test.php
```

Notice how the output between `UvDriver` and `EioDriver` differs, i.e. the 10 second repeat loop is never called when executing using `EioDriver`.

_composer.json is currently tracking my own fork of amphp/file, but the issue exists in 0.3 from packagist too_

**Comment by andrewmackrodt** [comment]
Closing after testing with a remote volume mount and non-blocking behaviour working as expected; if anyone else has a similar use case, UvDriver seems to offer better performance despite taking more polls to scan a directory.

**Comment by kelunik** [comment]
Thanks for further investigating!
