### ISSUE TITLE
Support for recursive mkdir

### ISSUE THREAD

**Issue by kelunik** [amphp/file#5]
There should be support for the recursive option like for [`mkdir`](http://php.net/manual/de/function.mkdir.php).

**Comment by bwoebi** [comment]
mkdir() internally just loops stat()'s and creates the directory if it doesn't exist yet. We'd have to do the same here with libuv/eio.

**Comment by kelunik** [comment]
Fine, but we should have it.

**Comment by staabm** [comment]
agree. our api should have similar features as one is used to from native php equivalents
