### ISSUE TITLE
Drop Handle interface in v2.0?

### ISSUE THREAD

**Issue by enumag** [amphp/file#51]
Should we drop this now? Or do you still want to keep it?

https://github.com/amphp/file/blob/f3d47a33ae01e3e151c8c0ddc3530d4ad7d1ce1e/src/Handle.php#L10-L12

**Comment by kelunik** [comment]
Deleting it doesn't seem to bring any benefit, so I'd just keep it.

**Comment by enumag** [comment]
Ok
