### ISSUE TITLE
stat failed

### ISSUE THREAD

**Issue by amirziaee** [amphp/file#65]
hi, i have an error in amphp when i init madeline
Exception:              stat(): stat failed for E:\php\telegram\tbot\session.madeline.safe.php in BlockingDriver.php:47
PHP Fatal error:  Uncaught \danog\MadelineProto\Exception: stat(): stat failed for E:\session.madeline.safe.php in phar://madeline-12bb67bc0618338b71ff507bd50a6b948d48e98e-80.phar/vendor/phabel-transpiler80.amphp/file/src/Driver/BlockingDriver.php:47

**Comment by enumag** [comment]
Unrelated to amphp, check online why the underlying php function fails for you.
 stat failed

**Comment by amirziaee** [comment]
the error is about my telegram session,i close it and its work.
