### ISSUE TITLE
creating new session failed

### ISSUE THREAD

**Issue by bravelighter** [amphp/file#66]
I cant start new session, I delete everything, update package , create new settings file but I get this error:

stat(): stat failed for E:\session.madeline.safe.php in BlockingDriver.php:47

The file session.madeline and it's not existed in the directory because it contains old data of old app.

**Comment by shredder2003** [comment]
the same problem on last windows 10

**Comment by Mateodioev** [comment]
Same problem in windows 11

**Comment by kelunik** [comment]
This issue and #36 seems to be specific to Madeline instead of being an issue in this library. /cc @danog
