### ISSUE TITLE
EIO createDirectoryRecursively() errors if it exists

### ISSUE THREAD

**Issue by Nadyita** [amphp/file#67]
When I'm using the EIO driver, calling `yield filesystem()->createDirectoryRecursively("/tmp");` errors out, while the BlockingDriver returns `new Success()`. It would be nice if they behave identical, so we don't have to wrap our calls in exists-checks.

On a related note, it took me very long to find this error, because the EIO error-messages seem to get mixed up. The actual error I got was 'No such file or directory', but when trying to reproduce the problem, I got the correct 'File exists' error. I will try to find a minimum example to reproduce this.

**Comment by kelunik** [comment]
Thanks for reporting and sorry for responding so late. This has now been fixed in https://github.com/amphp/file/commit/b8e3314417404e4e710ad4ab869e50ec3e5f0999.
