### ISSUE TITLE
Filesystem driver cache

### ISSUE THREAD

**Issue by tncrazvan** [amphp/file#68]
I'm trying to write a file watcher using `\Amp\File\getModificationTime` and a custom `listFilesRecursive`.

This is what `listFilesRecursive` does:
```php
use function Amp\call;
use function Amp\File\isDirectory;
use function Amp\File\listFiles;

use Amp\Promise;

function listFilesRecursive(string $path):Promise {
    return call(function() use ($path) {
        $items = yield listFiles($path);
        $files = [];
        foreach ($items as $item) {
            $filename = "$path/$item";
            $isDir    = yield isDirectory($filename);
            if ($isDir) {
                foreach (yield listFilesRecursive($filename) as $subItem) {
                    $files[] = $subItem;
                }
                continue;
            }

            $files[] = $filename;
        }
        return $files;
    });
}
```
I'm running `\Amp\File\getModificationTime` for each one of those files and everything repeats every X seconds.

The problem is that `getModificationTime` seems to return the wrong modification time when it runs more than once.

I noticed the filesystem driver is keeping a cache:

https://github.com/amphp/file/blob/013f592f3ece1440bcf8ce8a223147f8487d69d2/src/Driver/StatusCachingDriver.php#L19-L23

which is great for both performance and familiarity since the traditional [filemtime](https://www.php.net/manual/en/function.filemtime.php) also uses a cache.

In this case I don't really care if the `\Amp\File\*` functions are optimized for performance using that cache, I just care for their async nature, I want to avoid a bottleneck when the number of scanned files increases.

I noticed this method exists but it's private:
https://github.com/amphp/file/blob/013f592f3ece1440bcf8ce8a223147f8487d69d2/src/Driver/StatusCachingDriver.php#L127-L142

Is there a way to manually invalidate this cache similar to how traditional php does it with [clearstatcache](https://www.php.net/manual/en/function.clearstatcache.php)?

**Comment by kelunik** [comment]
Instead of exposing cache invalidation, I suggest using a custom Filesystem without the cache layer in between. If caching is desired per run, you could wrap your existing instance in a new StatusCachingDriver on each run.
