### ISSUE TITLE
Support for file locks

### ISSUE THREAD

**Issue by kelunik** [amphp/file#9]
We might need it to support file based sessions using UV / EIO. If those do not support it, we have to go with blocking standard library operations.

**Comment by kelunik** [comment]
@bwoebi @trowski Is that something we want? Should be in a 1.0 in that case, as it requires changes to the interface.

**Comment by kelunik** [comment]
UV doesn't support this, so we can't support it in the interface.

**Comment by kelunik** [comment]
Closing, as we have `FileMutex` in `amphp/sync`.

**Comment by bwoebi** [comment]
This is not quite the same thing. the FileMutex does not lock files, it creates a temporary lock file instead.

**Comment by kelunik** [comment]
Yes, read why it does that. It doesn't matter whether you lock a file directly or a file nearby.
